export const categories = [
  // Home & trades
  "HVAC Contractor",
  "Plumbing Services",
  "Roofing Contractor",
  "Electrician",
  "Landscaping Business",
  "Cleaning Service",
  "Auto Repair Shop",
  // Beauty & wellness
  "Beauty Salon",
  "Skin Care Clinic",
  "Hair Salon",
  "Nail Salon",
  "Med Spa",
  "Barber Shop",
  // Sports & fitness
  "Sports Club",
  "Fitness Center",
  "Yoga Studio",
  "Physical Therapy Clinic",
  // Professional services
  "Dental Clinic",
  "Chiropractic Clinic",
  "Law Firm",
  "Accounting Firm",
  "Marketing Agency",
  "Real Estate Agency",
  "Insurance Agency",
  "Photography Studio",
  // Retail & local
  "E-commerce Store",
  "Local Restaurant",
  "Coffee Shop",
  "Pet Grooming",
  "Veterinary Clinic",
  "Daycare Center",
];

export const geoData = {
  USA: {
    states: [
      "NY",
      "CA",
      "TX",
      "FL",
      "IL",
      "PA",
      "OH",
      "GA",
      "NC",
      "MI",
      "NJ",
      "VA",
      "WA",
      "AZ",
      "MA",
      "TN",
      "IN",
      "MO",
      "MD",
      "WI",
    ],
    zips: {
      NY: Array.from({ length: 20 }, (_, i) => (10001 + i).toString()),
      CA: Array.from({ length: 20 }, (_, i) => (90001 + i).toString()),
      TX: Array.from({ length: 20 }, (_, i) => (75001 + i).toString()),
      FL: Array.from({ length: 20 }, (_, i) => (33101 + i).toString()),
      IL: Array.from({ length: 20 }, (_, i) => (60601 + i).toString()),
      PA: Array.from({ length: 20 }, (_, i) => (19101 + i).toString()),
      OH: Array.from({ length: 20 }, (_, i) => (44101 + i).toString()),
      GA: Array.from({ length: 20 }, (_, i) => (30301 + i).toString()),
      NC: Array.from({ length: 20 }, (_, i) => (28201 + i).toString()),
      MI: Array.from({ length: 20 }, (_, i) => (48201 + i).toString()),
      NJ: Array.from({ length: 20 }, (_, i) =>
        (7001 + i).toString().padStart(5, "0")
      ),
      VA: Array.from({ length: 20 }, (_, i) => (23201 + i).toString()),
      WA: Array.from({ length: 20 }, (_, i) => (98101 + i).toString()),
      AZ: Array.from({ length: 20 }, (_, i) => (85001 + i).toString()),
      MA: Array.from({ length: 20 }, (_, i) =>
        (2101 + i).toString().padStart(5, "0")
      ),
      TN: Array.from({ length: 20 }, (_, i) => (37201 + i).toString()),
      IN: Array.from({ length: 20 }, (_, i) => (46201 + i).toString()),
      MO: Array.from({ length: 20 }, (_, i) => (63101 + i).toString()),
      MD: Array.from({ length: 20 }, (_, i) => (21201 + i).toString()),
      WI: Array.from({ length: 20 }, (_, i) => (53201 + i).toString()),
    },
  },
  UK: {
    states: [
      "London",
      "Manchester",
      "Birmingham",
      "Liverpool",
      "Leeds",
      "Glasgow",
      "Edinburgh",
      "Bristol",
      "Sheffield",
      "Cardiff",
      "Newcastle",
      "Belfast",
      "Nottingham",
      "Southampton",
      "Leicester",
      "Coventry",
      "Bradford",
      "Hull",
      "Stoke",
      "Wolverhampton",
    ],
    zips: {
      London: Array.from({ length: 20 }, (_, i) => "L" + (i + 1)),
      Manchester: Array.from({ length: 20 }, (_, i) => "M" + (i + 1)),
      Birmingham: Array.from({ length: 20 }, (_, i) => "B" + (i + 1)),
      Liverpool: Array.from({ length: 20 }, (_, i) => "L" + (i + 1)),
      Leeds: Array.from({ length: 20 }, (_, i) => "LS" + (i + 1)),
      Glasgow: Array.from({ length: 20 }, (_, i) => "G" + (i + 1)),
      Edinburgh: Array.from({ length: 20 }, (_, i) => "EH" + (i + 1)),
      Bristol: Array.from({ length: 20 }, (_, i) => "BS" + (i + 1)),
      Sheffield: Array.from({ length: 20 }, (_, i) => "S" + (i + 1)),
      Cardiff: Array.from({ length: 20 }, (_, i) => "CF" + (i + 1)),
      Newcastle: Array.from({ length: 20 }, (_, i) => "NE" + (i + 1)),
      Belfast: Array.from({ length: 20 }, (_, i) => "BT" + (i + 1)),
      Nottingham: Array.from({ length: 20 }, (_, i) => "NG" + (i + 1)),
      Southampton: Array.from({ length: 20 }, (_, i) => "SO" + (i + 1)),
      Leicester: Array.from({ length: 20 }, (_, i) => "LE" + (i + 1)),
      Coventry: Array.from({ length: 20 }, (_, i) => "CV" + (i + 1)),
      Bradford: Array.from({ length: 20 }, (_, i) => "BD" + (i + 1)),
      Hull: Array.from({ length: 20 }, (_, i) => "HU" + (i + 1)),
      Stoke: Array.from({ length: 20 }, (_, i) => "ST" + (i + 1)),
      Wolverhampton: Array.from({ length: 20 }, (_, i) => "WV" + (i + 1)),
    },
  },
  Canada: {
    states: [
      "Ontario",
      "Quebec",
      "British Columbia",
      "Alberta",
      "Manitoba",
      "Nova Scotia",
      "Saskatchewan",
      "New Brunswick",
      "Newfoundland",
      "PEI",
      "Yukon",
      "Nunavut",
      "NW Territories",
      "Ottawa",
      "Calgary",
      "Vancouver",
      "Edmonton",
      "Winnipeg",
      "Halifax",
      "Regina",
    ],
    zips: {
      Ontario: Array.from({ length: 20 }, (_, i) => "ON" + (i + 1)),
      Quebec: Array.from({ length: 20 }, (_, i) => "QC" + (i + 1)),
      "British Columbia": Array.from({ length: 20 }, (_, i) => "BC" + (i + 1)),
      Alberta: Array.from({ length: 20 }, (_, i) => "AB" + (i + 1)),
      Manitoba: Array.from({ length: 20 }, (_, i) => "MB" + (i + 1)),
      "Nova Scotia": Array.from({ length: 20 }, (_, i) => "NS" + (i + 1)),
      Saskatchewan: Array.from({ length: 20 }, (_, i) => "SK" + (i + 1)),
      "New Brunswick": Array.from({ length: 20 }, (_, i) => "NB" + (i + 1)),
      Newfoundland: Array.from({ length: 20 }, (_, i) => "NL" + (i + 1)),
      PEI: Array.from({ length: 20 }, (_, i) => "PE" + (i + 1)),
      Yukon: Array.from({ length: 20 }, (_, i) => "YT" + (i + 1)),
      Nunavut: Array.from({ length: 20 }, (_, i) => "NU" + (i + 1)),
      "NW Territories": Array.from({ length: 20 }, (_, i) => "NT" + (i + 1)),
      Ottawa: Array.from({ length: 20 }, (_, i) => "OT" + (i + 1)),
      Calgary: Array.from({ length: 20 }, (_, i) => "CG" + (i + 1)),
      Vancouver: Array.from({ length: 20 }, (_, i) => "VC" + (i + 1)),
      Edmonton: Array.from({ length: 20 }, (_, i) => "ED" + (i + 1)),
      Winnipeg: Array.from({ length: 20 }, (_, i) => "WN" + (i + 1)),
      Halifax: Array.from({ length: 20 }, (_, i) => "HX" + (i + 1)),
      Regina: Array.from({ length: 20 }, (_, i) => "RG" + (i + 1)),
    },
  },
  Australia: {
    states: [
      "NSW",
      "VIC",
      "QLD",
      "WA",
      "SA",
      "TAS",
      "ACT",
      "NT",
      "Other1",
      "Other2",
      "Other3",
      "Other4",
      "Other5",
      "Other6",
      "Other7",
      "Other8",
      "Other9",
      "Other10",
      "Other11",
      "Other12",
    ],
    zips: {
      NSW: Array.from({ length: 20 }, (_, i) => (2000 + i).toString()),
      VIC: Array.from({ length: 20 }, (_, i) => (3000 + i).toString()),
      QLD: Array.from({ length: 20 }, (_, i) => (4000 + i).toString()),
      WA: Array.from({ length: 20 }, (_, i) => (6000 + i).toString()),
      SA: Array.from({ length: 20 }, (_, i) => (5000 + i).toString()),
      TAS: Array.from({ length: 20 }, (_, i) => (7000 + i).toString()),
      ACT: Array.from({ length: 20 }, (_, i) => (2600 + i).toString()),
      NT: Array.from({ length: 20 }, (_, i) =>
        (800 + i).toString().padStart(4, "0")
      ),
      Other1: Array.from({ length: 20 }, (_, i) => (1000 + i).toString()),
      Other2: Array.from({ length: 20 }, (_, i) => (9000 + i).toString()),
      Other3: Array.from({ length: 20 }, (_, i) => (1100 + i).toString()),
      Other4: Array.from({ length: 20 }, (_, i) => (9100 + i).toString()),
      Other5: Array.from({ length: 20 }, (_, i) => (1200 + i).toString()),
      Other6: Array.from({ length: 20 }, (_, i) => (9200 + i).toString()),
      Other7: Array.from({ length: 20 }, (_, i) => (1300 + i).toString()),
      Other8: Array.from({ length: 20 }, (_, i) => (9300 + i).toString()),
      Other9: Array.from({ length: 20 }, (_, i) => (1400 + i).toString()),
      Other10: Array.from({ length: 20 }, (_, i) => (9400 + i).toString()),
      Other11: Array.from({ length: 20 }, (_, i) => (1500 + i).toString()),
      Other12: Array.from({ length: 20 }, (_, i) => (9500 + i).toString()),
    },
  },
} as const;

export type CountryKey = keyof typeof geoData;
